

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Norman_Manley_Institution_for_the_Impaired
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Norman_Manley_Institution_fo_the_ImpairedEntities1 : DbContext
{
    public Norman_Manley_Institution_fo_the_ImpairedEntities1()
        : base("name=Norman_Manley_Institution_fo_the_ImpairedEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ClassDetail> ClassDetails { get; set; }

    public virtual DbSet<DisabilityList> DisabilityLists { get; set; }

    public virtual DbSet<StudentGender> StudentGenders { get; set; }

    public virtual DbSet<DataforStudent> DataforStudents { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<User> Users { get; set; }

}

}

